import { ColorSchemeScript } from '@mantine/core';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { RootProvider } from './providers';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NextStack SaaS Starter - Organize Products Across Projects | Product Management Tool',
  description:
    'The modern product organization platform. Track inventory, manage projects, and collaborate with your team. Free to start, no credit card required.',
  keywords: [
    'product management',
    'project organization',
    'inventory tracking',
    'team collaboration',
    'product catalog',
    'project management tool',
    'inventory management software',
  ],
  authors: [{ name: 'NextStack SaaS Starter Team' }],
  creator: 'NextStack SaaS Starter',
  publisher: 'NextStack SaaS Starter',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://nextstack-saas-starter.com',
    title: 'NextStack SaaS Starter - Organize Products Across Projects',
    description:
      'The modern product organization platform. Track inventory, manage projects, and collaborate with your team.',
    siteName: 'NextStack SaaS Starter',
    // Dynamic OG image generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'NextStack SaaS Starter - Organize Products Across Projects',
    description:
      'The modern product organization platform. Track inventory and manage projects effortlessly.',
    // Dynamic Twitter image generated by src/app/twitter-image.tsx
    creator: '@nextstack-saas-starter',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: 'https://nextstack-saas-starter.com',
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
